server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: customer_service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/customers/**
            - id: account_service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/accounts/**

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: api-gateway
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.bank.account: DEBUG
